baseURL = "/"
languageCode = "en-us"
title = "One Up Smart Home"
theme = "oneupsmarthome"
description = "Smart home and home automation services in Fort Lauderdale, Miami, West Palm Beach and Jacksonville. We install Amazon echo devices, Google Home devices, smart WiFi light, smart bulbs and security cameras"
googleAnalytics = "UA-112061862-1"

[Params]
  RSSLink = "/index.xml"
  author = "One Up Smart Home"
  facebook = "oneupsmarthome"
  twitter = "oneupsmarthome"
  email = "info@oneupsmarthome.com"

[[menu.main]]
    name = "Home"
    weight = 100
    url = "/"
[[menu.main]]
    name = "Services"
    weight = 200
    url = "/services/"
[[menu.main]]
    name = "About Us"
    weight = 300
    url = "/about/"
[[menu.main]]
    name = "Contact"
    weight = 400
    url = "/contact/" 
[[menu.main]]
    name = "Book an Appointment"
    weight = 500
    url = "/appointment"         
[[menu.main]]
    name = "Contact Success"
    weight = 600
    url = "/contact-success/"     
